"""Plugin manifest data model."""

from __future__ import annotations

from pydantic import BaseModel, Field


class PluginManifest(BaseModel):
    """Metadata describing a Phoenix Engine adapter plugin.

    Every platform adapter must expose a manifest so the plugin loader can
    validate, register, and route URLs to it without importing core engine
    internals.
    """

    name: str = Field(..., description="Plugin identifier (lowercase, snake_case).")
    version: str = Field(..., description="Plugin version (semver).")
    description: str = Field(default="", description="Human-readable description.")
    author: str = Field(default="", description="Plugin author name or email.")
    platforms: list[str] = Field(
        default_factory=list,
        description="Platform identifiers handled by this plugin.",
    )
    url_patterns: list[str] = Field(
        default_factory=list,
        description="URL regex patterns this plugin can handle.",
    )
    strategies: list[str] = Field(
        default_factory=lambda: ["http", "browser"],
        description="Ordered list of supported collection strategies.",
    )
    dependencies: list[str] = Field(
        default_factory=list,
        description="PyPI dependencies required by the plugin.",
    )
    module_path: str | None = Field(
        default=None,
        description="Python module path where the adapter class is defined.",
    )
    class_name: str | None = Field(
        default=None,
        description="Adapter class name inside ``module_path``.",
    )
    requires_auth: bool = Field(
        default=False,
        description="Whether authenticated sessions are required for public data.",
    )
    supports_ai_fallback: bool = Field(
        default=True,
        description="Whether the adapter supports AI-assisted extraction fallback.",
    )
    generated: bool = Field(
        default=False,
        description="Whether this adapter was generated by PhoenixArchitect.",
    )
    confidence: float = Field(
        default=0.0,
        description="Adapter confidence score (0.0-1.0), e.g. from the Critic.",
    )


__all__ = ["PluginManifest"]
