"""Generate pytest fixtures and adapter unit tests from collected snapshots.

``FixtureGenerator`` converts the raw HTML snapshots produced by
``BrowserExplorer`` into a fixture directory and a runnable unit test file for
an adapter generated by PhoenixArchitect.
"""

from __future__ import annotations

import logging
import string
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml  # type: ignore[import-untyped]

if TYPE_CHECKING:
    from phoenix.architect.explorer import PageSnapshot

logger = logging.getLogger(__name__)


@dataclass
class FixtureSet:
    """Paths written by a fixture generation run."""

    platform: str
    fixture_dir: Path
    meta_path: Path
    test_path: Path
    html_paths: list[Path]


class FixtureGenerator:
    """Write HTML fixtures, metadata, and a generated adapter unit test."""

    def __init__(
        self,
        fixtures_dir: Path | str,
        tests_dir: Path | str,
    ) -> None:
        """Initialize the generator.

        Args:
            fixtures_dir: Directory where platform HTML fixtures are written
                (e.g. ``tests/fixtures/html``).
            tests_dir: Directory where generated unit tests are written
                (e.g. ``tests/unit``).
        """
        self._fixtures_dir = Path(fixtures_dir)
        self._tests_dir = Path(tests_dir)

    @staticmethod
    def _sanitize(platform: str) -> str:
        """Return a filesystem- and module-safe platform identifier."""
        sanitized = platform.lower().strip().replace("-", "_").replace(" ", "_")
        return "".join(c for c in sanitized if c.isalnum() or c == "_").strip("_")

    @staticmethod
    def _class_name(platform: str) -> str:
        """Return the generated adapter class name for ``platform``."""
        return f"{platform.title().replace('_', '')}Adapter"

    def generate(
        self,
        platform: str,
        snapshots: list[PageSnapshot],
        extracted_outputs: list[dict[str, Any]] | None = None,
    ) -> FixtureSet:
        """Generate fixtures and a unit test for ``platform``.

        Args:
            platform: Platform identifier (snake_case).
            snapshots: HTML snapshots collected from the target site.
            extracted_outputs: Optional extracted field dictionaries for each
                snapshot, used to populate expected values in ``meta.yaml``.

        Returns:
            A ``FixtureSet`` describing the generated artifacts.
        """
        safe_platform = self._sanitize(platform)
        fixture_dir = self._fixtures_dir / safe_platform
        fixture_dir.mkdir(parents=True, exist_ok=True)

        extracted_outputs = extracted_outputs or [{} for _ in snapshots]
        if len(extracted_outputs) != len(snapshots):
            msg = "snapshots and extracted_outputs must have the same length"
            raise ValueError(msg)

        html_paths: list[Path] = []
        meta_entries: list[dict[str, Any]] = []
        for index, snapshot in enumerate(snapshots, start=1):
            html_name = f"page_{index}.html"
            html_path = fixture_dir / html_name
            html_path.write_text(snapshot.html, encoding="utf-8")
            html_paths.append(html_path)

            expected = self._derive_expected(extracted_outputs[index - 1])
            meta_entries.append(
                {
                    "source_url": snapshot.url,
                    "capture_date": datetime.now(UTC).isoformat(),
                    "fixture": html_name,
                    "expected_fields": expected,
                    "notes": (
                        "Sanitize personal information before committing. "
                        "Replace real identifiers with test values."
                    ),
                },
            )

        meta_path = self._write_meta(fixture_dir, meta_entries)
        sample_url = snapshots[0].url if snapshots else ""
        test_path = self._write_test(safe_platform, html_name, sample_url)

        logger.info(
            "Generated %d fixture(s) for platform '%s' at %s",
            len(snapshots),
            safe_platform,
            fixture_dir,
        )
        return FixtureSet(
            platform=safe_platform,
            fixture_dir=fixture_dir,
            meta_path=meta_path,
            test_path=test_path,
            html_paths=html_paths,
        )

    @staticmethod
    def _derive_expected(extracted: dict[str, Any]) -> dict[str, Any]:
        """Derive conservative expected field assertions from extracted data."""
        expected: dict[str, Any] = {}
        for field, value in extracted.items():
            if field.endswith("_confidence") or field == "selectors_used":
                continue
            if isinstance(value, list):
                expected[field] = {"type": "list", "min_length": 0}
            elif isinstance(value, (int, float)):
                expected[field] = {"type": "number"}
            elif isinstance(value, str) and value.strip():
                expected[field] = {"type": "string", "non_empty": True}
            elif value is None:
                expected[field] = {"type": "optional"}
            else:
                expected[field] = {"type": "present"}
        return expected

    def _write_meta(self, fixture_dir: Path, entries: list[dict[str, Any]]) -> Path:
        """Write ``meta.yaml`` to ``fixture_dir``."""
        meta_path = fixture_dir / "meta.yaml"
        meta_path.write_text(yaml.safe_dump(entries, sort_keys=False), encoding="utf-8")
        return meta_path

    def _write_test(self, platform: str, fixture_name: str, url: str) -> Path:
        """Write the generated unit test file for ``platform``."""
        self._tests_dir.mkdir(parents=True, exist_ok=True)
        class_name = self._class_name(platform)
        template = string.Template(
            '''"""Auto-generated unit test for the $platform adapter.

This test was generated from a collected HTML snapshot. Review the fixture for
sanitized content before relying on these assertions in CI.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from phoenix.adapters.generated.$platform import $class_name
from phoenix.models.document import RawResponse
from phoenix.models.output import UnifiedOutput

pytestmark = pytest.mark.unit

FIXTURES_DIR = Path(__file__).parent.parent / "fixtures" / "html" / "$platform"
URL = "$url"


@pytest.fixture
def adapter() -> $class_name:
    """Return a $platform adapter instance."""
    return $class_name()


@pytest.fixture
def raw_response() -> RawResponse:
    """Return a RawResponse wrapping the collected snapshot."""
    html = (FIXTURES_DIR / "$fixture_name").read_text(encoding="utf-8")
    return RawResponse(
        url=URL,
        final_url=URL,
        status_code=200,
        headers={"content-type": "text/html"},
        html=html,
        strategy="browser",
    )


@pytest.mark.asyncio
async def test_extract_required_fields(adapter: $class_name, raw_response: RawResponse) -> None:
    """Extract returns the expected fields from the snapshot."""
    extracted = await adapter.extract(raw_response)

    assert extracted is not None
    assert isinstance(extracted, dict)
    # The fixture meta.yaml lists the expected fields for this snapshot.
    assert extracted.get("selectors_used") is not None


@pytest.mark.asyncio
async def test_normalize_returns_unified_output(
    adapter: $class_name,
    raw_response: RawResponse,
) -> None:
    """Normalization produces a valid UnifiedOutput."""
    extracted = await adapter.extract(raw_response)
    output = await adapter.normalize(extracted, URL, "browser")

    assert isinstance(output, UnifiedOutput)
    assert output.url == URL
    assert output.platform == "$platform"


@pytest.mark.asyncio
async def test_adapter_rejects_login_wall(adapter: $class_name) -> None:
    """The adapter flags login-wall HTML as non-public."""
    html = "<html><body>Please log in to view this content</body></html>"
    raw = RawResponse(
        url=URL,
        final_url=URL,
        status_code=200,
        headers={"content-type": "text/html"},
        html=html,
        strategy="browser",
    )

    assert adapter._is_public_content(raw.html) is False  # noqa: SLF001
''',
        )
        test_source = template.substitute(
            platform=platform,
            class_name=class_name,
            fixture_name=fixture_name,
            url=url,
        )
        test_path = self._tests_dir / f"test_{platform}_adapter.py"
        test_path.write_text(test_source, encoding="utf-8")
        return test_path


__all__ = ["FixtureGenerator", "FixtureSet"]
